// Auto-generated by Supabase MCP `generate_typescript_types`.
// Do not edit by hand.
// To regenerate: call the Supabase MCP tool with project_id nwvswntqrqqtwzrhzpmi
// or run: npx supabase gen types typescript --project-id nwvswntqrqqtwzrhzpmi > lib/db/types.ts
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      AIConversation: {
        Row: {
          contextType: string
          createdAt: string
          id: string
          messages: Json
          updatedAt: string
          userId: string
        }
        Insert: {
          contextType: string
          createdAt?: string
          id?: string
          messages: Json
          updatedAt: string
          userId: string
        }
        Update: {
          contextType?: string
          createdAt?: string
          id?: string
          messages?: Json
          updatedAt?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "AIConversation_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "User"
            referencedColumns: ["id"]
          },
        ]
      }
      BrokerConnection: {
        Row: {
          accountId: string | null
          brokerName: string
          flexQueryIdActivity: string
          flexTokenEncrypted: string
          id: string
          isActive: boolean
          lastPriceSyncAt: string | null
          lastPriceSyncStatus: string | null
          lastSyncAt: string | null
          lastSyncError: string | null
          lastSyncStatus: string | null
          pollingIntervalMin: number
          pricePollingIntervalMin: number
          userId: string
        }
        Insert: {
          accountId?: string | null
          brokerName: string
          flexQueryIdActivity: string
          flexTokenEncrypted: string
          id?: string
          isActive?: boolean
          lastPriceSyncAt?: string | null
          lastPriceSyncStatus?: string | null
          lastSyncAt?: string | null
          lastSyncError?: string | null
          lastSyncStatus?: string | null
          pollingIntervalMin?: number
          pricePollingIntervalMin?: number
          userId: string
        }
        Update: {
          accountId?: string | null
          brokerName?: string
          flexQueryIdActivity?: string
          flexTokenEncrypted?: string
          id?: string
          isActive?: boolean
          lastPriceSyncAt?: string | null
          lastPriceSyncStatus?: string | null
          lastSyncAt?: string | null
          lastSyncError?: string | null
          lastSyncStatus?: string | null
          pollingIntervalMin?: number
          pricePollingIntervalMin?: number
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "BrokerConnection_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "User"
            referencedColumns: ["id"]
          },
        ]
      }
      BrokerEvent: {
        Row: {
          eventType: string
          id: string
          processedAt: string | null
          processingError: string | null
          processingStatus: string
          rawPayload: Json
          receivedAt: string
          source: string
          userId: string
        }
        Insert: {
          eventType: string
          id?: string
          processedAt?: string | null
          processingError?: string | null
          processingStatus: string
          rawPayload: Json
          receivedAt?: string
          source: string
          userId: string
        }
        Update: {
          eventType?: string
          id?: string
          processedAt?: string | null
          processingError?: string | null
          processingStatus?: string
          rawPayload?: Json
          receivedAt?: string
          source?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "BrokerEvent_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "User"
            referencedColumns: ["id"]
          },
        ]
      }
      Order: {
        Row: {
          brokerClientAccountId: string | null
          brokerExecId: string
          brokerOrderId: string | null
          brokerTradeId: string | null
          commission: number | null
          commissionCurrency: string | null
          currency: string | null
          exchange: string | null
          executedAt: string
          id: string
          netCash: number | null
          orderTime: string | null
          orderType: string | null
          price: number
          proceeds: number | null
          quantity: number
          rawPayload: Json
          side: string
          tax: number | null
          tradeDate: string | null
          tradeId: string
          userId: string
        }
        Insert: {
          brokerClientAccountId?: string | null
          brokerExecId: string
          brokerOrderId?: string | null
          brokerTradeId?: string | null
          commission?: number | null
          commissionCurrency?: string | null
          currency?: string | null
          exchange?: string | null
          executedAt: string
          id?: string
          netCash?: number | null
          orderTime?: string | null
          orderType?: string | null
          price: number
          proceeds?: number | null
          quantity: number
          rawPayload: Json
          side: string
          tax?: number | null
          tradeDate?: string | null
          tradeId: string
          userId: string
        }
        Update: {
          brokerClientAccountId?: string | null
          brokerExecId?: string
          brokerOrderId?: string | null
          brokerTradeId?: string | null
          commission?: number | null
          commissionCurrency?: string | null
          currency?: string | null
          exchange?: string | null
          executedAt?: string
          id?: string
          netCash?: number | null
          orderTime?: string | null
          orderType?: string | null
          price?: number
          proceeds?: number | null
          quantity?: number
          rawPayload?: Json
          side?: string
          tax?: number | null
          tradeDate?: string | null
          tradeId?: string
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "Order_tradeId_fkey"
            columns: ["tradeId"]
            isOneToOne: false
            referencedRelation: "Trade"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "Order_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "User"
            referencedColumns: ["id"]
          },
        ]
      }
      Trade: {
        Row: {
          actualR: number | null
          assetType: string
          avgEntryPrice: number
          avgExitPrice: number | null
          closedAt: string | null
          didRight: string | null
          direction: string
          emotionalState: string | null
          executionQuality: number | null
          externalRefId: string | null
          id: string
          lastKnownPrice: number | null
          lastPriceUpdateAt: string | null
          multiplier: number
          notes: string | null
          openedAt: string
          realizedPnl: number | null
          result: string | null
          rMultipleEntry: number | null
          setupType: string | null
          status: string
          stopPrice: number | null
          targetPrice: number | null
          ticker: string
          totalCommission: number | null
          totalQuantity: number
          totalQuantityOpened: number
          userId: string
          wouldChange: string | null
        }
        Insert: {
          actualR?: number | null
          assetType?: string
          avgEntryPrice: number
          avgExitPrice?: number | null
          closedAt?: string | null
          didRight?: string | null
          direction: string
          emotionalState?: string | null
          executionQuality?: number | null
          externalRefId?: string | null
          id?: string
          lastKnownPrice?: number | null
          lastPriceUpdateAt?: string | null
          multiplier?: number
          notes?: string | null
          openedAt: string
          realizedPnl?: number | null
          result?: string | null
          rMultipleEntry?: number | null
          setupType?: string | null
          status: string
          stopPrice?: number | null
          targetPrice?: number | null
          ticker: string
          totalCommission?: number | null
          totalQuantity: number
          totalQuantityOpened: number
          userId: string
          wouldChange?: string | null
        }
        Update: {
          actualR?: number | null
          assetType?: string
          avgEntryPrice?: number
          avgExitPrice?: number | null
          closedAt?: string | null
          didRight?: string | null
          direction?: string
          emotionalState?: string | null
          executionQuality?: number | null
          externalRefId?: string | null
          id?: string
          lastKnownPrice?: number | null
          lastPriceUpdateAt?: string | null
          multiplier?: number
          notes?: string | null
          openedAt?: string
          realizedPnl?: number | null
          result?: string | null
          rMultipleEntry?: number | null
          setupType?: string | null
          status?: string
          stopPrice?: number | null
          targetPrice?: number | null
          ticker?: string
          totalCommission?: number | null
          totalQuantity?: number
          totalQuantityOpened?: number
          userId?: string
          wouldChange?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "Trade_userId_fkey"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "User"
            referencedColumns: ["id"]
          },
        ]
      }
      User: {
        Row: {
          createdAt: string
          email: string
          id: string
          name: string | null
          settings: Json
        }
        Insert: {
          createdAt?: string
          email: string
          id?: string
          name?: string | null
          settings?: Json
        }
        Update: {
          createdAt?: string
          email?: string
          id?: string
          name?: string | null
          settings?: Json
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      reverse_position:
        | {
            Args: {
              close_order: Json
              close_trade_id: string
              close_update: Json
              open_order: Json
              open_trade: Json
            }
            Returns: Json
          }
        | {
            Args: {
              p_actual_r: number
              p_avg_exit_price: number
              p_close_at: string
              p_close_order: Json
              p_close_status: string
              p_close_trade_id: string
              p_new_order: Json
              p_new_trade: Json
              p_realized_pnl: number
              p_result: string
              p_total_commission: number
            }
            Returns: undefined
          }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
