// ESLint 9 flat config.
//
// The repo previously had NO eslint config at all — `npm run lint` was
// `next lint`, which Next.js 16 removed, so linting had silently been a no-op
// for the whole Next-16 era. eslint-config-next@16 already exports flat-config
// arrays, so this needs no FlatCompat/@eslint/eslintrc shim.
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypeScript from 'eslint-config-next/typescript'

const config = [
  {
    ignores: [
      '.next/**',
      'out/**',
      'build/**',
      'coverage/**',
      'node_modules/**',
      '.vercel/**',
      '.claude/**',
      'next-env.d.ts',         // generated by `next build`
      'public/**',
      'marketing-campaign/**', // standalone assets, not part of the app build
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypeScript,

  {
    rules: {
      // OFF — permanent, not debt.
      // This rule exists to catch stray apostrophes/quotes in English JSX prose.
      // Every violation in this repo is an ASCII `"` used as Hebrew gershayim,
      // which is correct punctuation here: בד"כ, סה"כ, "טריידים חסרים". Escaping
      // them to &quot; would make the Hebrew copy unreadable in source for no
      // rendering benefit. See .claude/rules/rtl-and-language.md.
      'react/no-unescaped-entities': 'off',

      // `_`-prefixed args/vars are the established "intentionally unused"
      // convention in this codebase (mock fetch signatures, tuple destructuring).
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // WARN — real signal, deliberately not failing the build *yet*.
      //
      // These two ship with eslint-plugin-react-hooks v6 (React Compiler rules)
      // and were never enforced here, so they surface ~30 pre-existing hits
      // across ~20 components. Fixing them means genuine hook refactors with
      // real regression risk, which does not belong bundled into a tooling
      // migration. Kept visible in `npm run lint` output rather than switched
      // off, so the debt stays honest instead of disappearing.
      //
      // Two notes for whoever picks this up:
      //  - All 12 `refs` hits are in one file, components/research/shell.tsx.
      //  - Some `set-state-in-effect` hits are the *intended* fix for something
      //    else: e.g. admin-health-dashboard.tsx defers Date.now() to an effect
      //    specifically to avoid a hydration mismatch. Those need a different
      //    pattern (useSyncExternalStore), not a naive inlining.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
    },
  },
]

export default config
