// ESLint 9 flat config.
//
// The repo previously had NO eslint config at all — `npm run lint` was
// `next lint`, which Next.js 16 removed, so linting had silently been a no-op
// for the whole Next-16 era. eslint-config-next@16 already exports flat-config
// arrays, so this needs no FlatCompat/@eslint/eslintrc shim.
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypeScript from 'eslint-config-next/typescript'

const config = [
  {
    ignores: [
      '.next/**',
      'out/**',
      'build/**',
      'coverage/**',
      'node_modules/**',
      '.vercel/**',
      '.claude/**',
      'next-env.d.ts',         // generated by `next build`
      'public/**',
      'marketing-campaign/**', // standalone assets, not part of the app build
    ],
  },

  ...nextCoreWebVitals,
  ...nextTypeScript,

  {
    rules: {
      // OFF — permanent, not debt.
      // This rule exists to catch stray apostrophes/quotes in English JSX prose.
      // Every violation in this repo is an ASCII `"` used as Hebrew gershayim,
      // which is correct punctuation here: בד"כ, סה"כ, "טריידים חסרים". Escaping
      // them to &quot; would make the Hebrew copy unreadable in source for no
      // rendering benefit. See .claude/rules/rtl-and-language.md.
      'react/no-unescaped-entities': 'off',

      // `_`-prefixed args/vars are the established "intentionally unused"
      // convention in this codebase (mock fetch signatures, tuple destructuring).
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],

      // ERROR. These two ship with eslint-plugin-react-hooks v6 (the React
      // Compiler rules) and landed with ~30 pre-existing violations, which were
      // parked at 'warn' for one commit so the tooling migration wouldn't drag
      // a risky refactor along with it. All of them are now fixed, so the rules
      // are enforced — do not downgrade one to silence a new hit.
      //
      // The recurring fixes, if you trip these:
      //  - refs: don't hand a ref-reading closure to a plain function call
      //    during render. React.cloneElement was the offender; context is the
      //    replacement (see components/research/shell.tsx PairSlotContext).
      //  - set-state-in-effect, browser-only value (localStorage, cookies,
      //    Notification.permission): useHydrated() from lib/hooks, then adopt
      //    the real value in a render-phase adjustment. Date.now() specifically
      //    cannot be read in render at all (react-hooks/purity) — use
      //    useClientNow() from lib/hooks instead.
      //  - set-state-in-effect, state mirroring a prop: compare against the
      //    previous prop during render, don't sync it in an effect.
      //  - set-state-in-effect, "reset everything when the id changes": give
      //    the component a key at the mount site.
      'react-hooks/set-state-in-effect': 'error',
      'react-hooks/refs': 'error',
    },
  },
]

export default config
